# https://www.xaprb.com/blog/how-to-style-images-with-markdown/
# make images wide like theverge longform by default
# have some markdown tag to make images inline
# ![Kitten](/media/2018/08/kitten.jpg){:.thumbnail.bordered}
# then test in your photo pages with some description

# -top border (typography.scss -> body)
# Command to build with disqus
# JEKYLL_ENV=production bundle exec jekyll build
# pw: kk

#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bob Lou
email: rlou@upenn.edu
description: > # this means to ignore newlines until "baseurl:"
  Robert "Bob" Lou is a MD/MBA student at the Perelman School of Medicine and Wharton at the University of Pennsylvania. This is his personal blog and website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.boblou.com" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: github

github_username: robert-lou
instagram_username: boboolou
linkedin_username: boblou
disqus_shortname: rl2595

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
